sudo: required

services:
  - docker

before_install:
  - docker image build -t keidrun/coinietrade-docs:latest -f Dockerfile.dev .

script:
  - docker container run -d --rm --name web keidrun/coinietrade-docs:latest yarn dev
  - docker container exec -i web yarn build
  - docker container cp web:/app/_book .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _book
  fqdn: docs.coinietrade.com
  on:
    branch: master
